### ISSUE TITLE
Number command

### ISSUE THREAD

**Issue by catsolike** [asmpro7/VolumeFlow#1]
Can you add feature: if write 'vo <number>', sound volume becomes level <number>. <number> from 0 to 100.
Example: 'vo 28' - sound volume becomes 28
![image](https://github.com/asmpro7/VolumeFlow/assets/74639684/dedbab2d-ac1f-4745-9dc6-0cd0e61851f3)
![image](https://github.com/asmpro7/VolumeFlow/assets/74639684/d7ec734b-7b64-44d1-9580-56dd2d07938a)

**Comment by asmpro7** [comment]
it add [here](https://github.com/asmpro7/VolumeFlow/releases/tag/v1.1.0)
in v1.1.0 
![image](https://github.com/asmpro7/VolumeFlow/assets/114514662/48356fe3-33b6-418a-b64e-c9d2e2ddf58b)
![image](https://github.com/asmpro7/VolumeFlow/assets/114514662/21909aa4-4078-4f2c-aa1f-bd42c28647ff)
update it and enjoy 
thx for your request

**Comment by catsolike** [comment]
Wow, you're so fast! Thanks for update
